### ISSUE TITLE
Дата

### ISSUE THREAD

**Issue by ShibalovRoman** [Leechristmas/Staffinfo#2]
Когда выбираешь поле с датой, она пропечатывается на сегодняшнюю, собстна, ты думаешь "а зачем лезть в календарь, если дата уже напечатана?", и заполняешь дальше. А дата то не принята, чтобы ее приняло надо выбрать ее в календаре. Отсюда вывод, что или надо сразу дату принимать, или не печатать ее сразу по клику

**Comment by ShibalovRoman** [comment]
Сообщение об успешной авторизации закрывает полезную область, хотя по центру есть овер много свободного места

**Comment by Leechristmas** [comment]
Fixed: when a picker is focused the date is set to the current date.

**Comment by Leechristmas** [comment]
As for a message: it is shown only for 5 seconds.

**Comment by Leechristmas** [comment]
Resolved.
