### ISSUE TITLE
Полоска выбора выслуги

### ISSUE THREAD

**Issue by ShibalovRoman** [Leechristmas/Staffinfo#22]
когда тянешь за одну полосочку, едет вторая, один раз даже они поменялись местами знатно так. Тестил на серединах значений, там оно наиболее заметно

**Comment by ShibalovRoman** [comment]
точнее за точку крайнюю, а не за полосочку

**Comment by Leechristmas** [comment]
It is happened because of changing the scale of the slider. Check the changing values.
